package CRUD;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Emil
 */
public class Core extends javax.swing.JFrame {
    final Database_Connection Data = new Database_Connection();
    final ContactHandler Ops = new ContactHandler();
                
    /**
     * Creates new form Core
     */
    public Core() {
        setTitle("Contacts App - Java CRUD");
        setBounds(10, 50, 1330, 585);
        initComponents();
        Initializer();
        icon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewContact = new javax.swing.JDialog();
        Header2 = new javax.swing.JPanel();
        New_Con = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Company = new javax.swing.JLabel();
        Pos = new javax.swing.JLabel();
        Tel = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Notas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NameField = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        LNameField = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        CorpField = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        PosField = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        NumField = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        EmailField = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        NotesField = new javax.swing.JTextPane();
        CancelBtn = new javax.swing.JButton();
        SaveContact = new javax.swing.JButton();
        Contact_Pic = new javax.swing.JPanel();
        nonePic = new javax.swing.JLabel();
        UploadPic = new javax.swing.JButton();
        Nombre2 = new javax.swing.JLabel();
        jScrollPane20 = new javax.swing.JScrollPane();
        IDField = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        filePath = new javax.swing.JTextPane();
        MultiPanel = new javax.swing.JDialog();
        Header5 = new javax.swing.JPanel();
        New_Con2 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        InfoNotes = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        InfoLast = new javax.swing.JTextPane();
        Nombre1 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        InfoCompany = new javax.swing.JTextPane();
        Apellido1 = new javax.swing.JLabel();
        Company1 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        InfoPos = new javax.swing.JTextPane();
        Pos1 = new javax.swing.JLabel();
        Tel1 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        InfoTel = new javax.swing.JTextPane();
        Email1 = new javax.swing.JLabel();
        Notas1 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        InfoEmail = new javax.swing.JTextPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        InfoName = new javax.swing.JTextPane();
        Contact_Pic1 = new javax.swing.JPanel();
        nonePic1 = new javax.swing.JLabel();
        PanelDone = new javax.swing.JButton();
        SearchCon = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        SearchField = new javax.swing.JTextPane();
        UpdateCon = new javax.swing.JButton();
        EditCon = new javax.swing.JButton();
        DelCon = new javax.swing.JButton();
        jScrollPane21 = new javax.swing.JScrollPane();
        IDInfo = new javax.swing.JTextPane();
        Nombre3 = new javax.swing.JLabel();
        ImportContacts = new javax.swing.JDialog();
        OpenCon = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        FilePath = new javax.swing.JTextPane();
        CancelImp = new javax.swing.JButton();
        SaveCon = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ImpCon = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        ImportTable = new javax.swing.JTable();
        Background = new javax.swing.JPanel();
        Options = new javax.swing.JPanel();
        AddBtn = new javax.swing.JButton();
        ImportBtn = new javax.swing.JButton();
        iconAdd = new javax.swing.JLabel();
        iconImport = new javax.swing.JLabel();
        iconEdit1 = new javax.swing.JLabel();
        OpenPanel = new javax.swing.JButton();
        Container = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ContactsContainer = new javax.swing.JTable();
        Close = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        RefreshBtn = new javax.swing.JButton();

        NewContact.setMinimumSize(new java.awt.Dimension(875, 320));
        NewContact.setResizable(false);

        Header2.setBackground(new java.awt.Color(2, 136, 209));

        New_Con.setFont(new java.awt.Font("Ubuntu Light", 1, 16)); // NOI18N
        New_Con.setForeground(new java.awt.Color(255, 255, 255));
        New_Con.setText("Nuevo Contacto");

        javax.swing.GroupLayout Header2Layout = new javax.swing.GroupLayout(Header2);
        Header2.setLayout(Header2Layout);
        Header2Layout.setHorizontalGroup(
            Header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header2Layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(New_Con)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Header2Layout.setVerticalGroup(
            Header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(New_Con, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        Nombre.setFont(new java.awt.Font("Ubuntu Light", 0, 17)); // NOI18N
        Nombre.setText("Nombre:");

        Apellido.setFont(new java.awt.Font("Ubuntu Light", 0, 17)); // NOI18N
        Apellido.setText("Apellido:");

        Company.setFont(new java.awt.Font("Ubuntu Light", 0, 17)); // NOI18N
        Company.setText("Empresa:");

        Pos.setFont(new java.awt.Font("Ubuntu Light", 0, 17)); // NOI18N
        Pos.setText("Posición:");

        Tel.setFont(new java.awt.Font("Ubuntu Light", 0, 17)); // NOI18N
        Tel.setText("Teléfono:");

        Email.setFont(new java.awt.Font("Ubuntu Light", 0, 17)); // NOI18N
        Email.setText("Email:");

        Notas.setFont(new java.awt.Font("Ubuntu Light", 0, 17)); // NOI18N
        Notas.setText("Notas:");

        jScrollPane1.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N

        NameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        NameField.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane1.setViewportView(NameField);

        jScrollPane2.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane2.setMinimumSize(new java.awt.Dimension(3, 23));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(5, 25));

        LNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        LNameField.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane2.setViewportView(LNameField);

        jScrollPane3.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane3.setMinimumSize(new java.awt.Dimension(3, 23));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(5, 25));

        CorpField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        CorpField.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane3.setViewportView(CorpField);

        jScrollPane4.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane4.setMinimumSize(new java.awt.Dimension(3, 23));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(5, 25));

        PosField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        PosField.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane4.setViewportView(PosField);

        jScrollPane8.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane8.setMinimumSize(new java.awt.Dimension(3, 23));

        NumField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        NumField.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane8.setViewportView(NumField);

        jScrollPane9.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane9.setMinimumSize(new java.awt.Dimension(3, 23));

        EmailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        EmailField.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane9.setViewportView(EmailField);

        jScrollPane10.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane10.setMinimumSize(new java.awt.Dimension(3, 23));

        NotesField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        NotesField.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane10.setViewportView(NotesField);

        CancelBtn.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        CancelBtn.setText("Cancelar");
        CancelBtn.setFocusPainted(false);
        CancelBtn.setPreferredSize(new java.awt.Dimension(75, 25));

        SaveContact.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        SaveContact.setText("Guardar");
        SaveContact.setFocusPainted(false);
        SaveContact.setPreferredSize(new java.awt.Dimension(75, 25));

        Contact_Pic.setBackground(new java.awt.Color(255, 255, 255));
        Contact_Pic.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Contact_Pic.setMaximumSize(new java.awt.Dimension(150, 150));
        Contact_Pic.setMinimumSize(new java.awt.Dimension(150, 150));
        Contact_Pic.setPreferredSize(new java.awt.Dimension(150, 150));

        nonePic.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N

        javax.swing.GroupLayout Contact_PicLayout = new javax.swing.GroupLayout(Contact_Pic);
        Contact_Pic.setLayout(Contact_PicLayout);
        Contact_PicLayout.setHorizontalGroup(
            Contact_PicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contact_PicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nonePic, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        Contact_PicLayout.setVerticalGroup(
            Contact_PicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contact_PicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nonePic, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );

        UploadPic.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        UploadPic.setText("Subir Foto");
        UploadPic.setFocusPainted(false);

        Nombre2.setFont(new java.awt.Font("Ubuntu Light", 0, 17)); // NOI18N
        Nombre2.setText("ID:");

        jScrollPane20.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N

        IDField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        IDField.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        IDField.setEnabled(false);
        jScrollPane20.setViewportView(IDField);

        filePath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        filePath.setEnabled(false);
        jScrollPane7.setViewportView(filePath);

        javax.swing.GroupLayout NewContactLayout = new javax.swing.GroupLayout(NewContact.getContentPane());
        NewContact.getContentPane().setLayout(NewContactLayout);
        NewContactLayout.setHorizontalGroup(
            NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(NewContactLayout.createSequentialGroup()
                .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewContactLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Contact_Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Apellido, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Company, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Tel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Email, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Notas, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(NewContactLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(UploadPic)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(SaveContact, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        NewContactLayout.setVerticalGroup(
            NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewContactLayout.createSequentialGroup()
                .addComponent(Header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Contact_Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NewContactLayout.createSequentialGroup()
                        .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewContactLayout.createSequentialGroup()
                                .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pos)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewContactLayout.createSequentialGroup()
                                .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nombre2)
                                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewContactLayout.createSequentialGroup()
                                .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(NewContactLayout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(NewContactLayout.createSequentialGroup()
                                .addComponent(Tel)
                                .addGap(18, 18, 18)
                                .addComponent(Email)
                                .addGap(15, 15, 15)
                                .addComponent(Notas))
                            .addGroup(NewContactLayout.createSequentialGroup()
                                .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nombre))
                                .addGap(18, 18, 18)
                                .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Apellido)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Company)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewContactLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SaveContact, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(NewContactLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(NewContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UploadPic, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jScrollPane7))))
                .addContainerGap())
        );

        MultiPanel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        MultiPanel.setMinimumSize(new java.awt.Dimension(860, 340));

        Header5.setBackground(new java.awt.Color(2, 136, 209));

        New_Con2.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        New_Con2.setForeground(new java.awt.Color(255, 255, 255));
        New_Con2.setText("Administar Contactos");

        javax.swing.GroupLayout Header5Layout = new javax.swing.GroupLayout(Header5);
        Header5.setLayout(Header5Layout);
        Header5Layout.setHorizontalGroup(
            Header5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header5Layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(New_Con2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Header5Layout.setVerticalGroup(
            Header5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(New_Con2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane11.setEnabled(false);
        jScrollPane11.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane11.setMinimumSize(new java.awt.Dimension(3, 23));

        InfoNotes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        InfoNotes.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        InfoNotes.setEnabled(false);
        jScrollPane11.setViewportView(InfoNotes);

        jScrollPane13.setEnabled(false);
        jScrollPane13.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane13.setMinimumSize(new java.awt.Dimension(3, 23));
        jScrollPane13.setPreferredSize(new java.awt.Dimension(5, 25));

        InfoLast.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        InfoLast.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        InfoLast.setEnabled(false);
        jScrollPane13.setViewportView(InfoLast);

        Nombre1.setFont(new java.awt.Font("Ubuntu Light", 0, 17)); // NOI18N
        Nombre1.setText("Nombre:");

        jScrollPane14.setEnabled(false);
        jScrollPane14.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane14.setMinimumSize(new java.awt.Dimension(3, 23));
        jScrollPane14.setPreferredSize(new java.awt.Dimension(5, 25));

        InfoCompany.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        InfoCompany.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        InfoCompany.setEnabled(false);
        jScrollPane14.setViewportView(InfoCompany);

        Apellido1.setFont(new java.awt.Font("Ubuntu Light", 0, 17)); // NOI18N
        Apellido1.setText("Apellido:");

        Company1.setFont(new java.awt.Font("Ubuntu Light", 0, 17)); // NOI18N
        Company1.setText("Compañia:");

        jScrollPane15.setEnabled(false);
        jScrollPane15.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane15.setMinimumSize(new java.awt.Dimension(3, 23));
        jScrollPane15.setPreferredSize(new java.awt.Dimension(5, 25));

        InfoPos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        InfoPos.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        InfoPos.setEnabled(false);
        jScrollPane15.setViewportView(InfoPos);

        Pos1.setFont(new java.awt.Font("Ubuntu Light", 0, 17)); // NOI18N
        Pos1.setText("Posición:");

        Tel1.setFont(new java.awt.Font("Ubuntu Light", 0, 17)); // NOI18N
        Tel1.setText("Teléfono:");

        jScrollPane16.setEnabled(false);
        jScrollPane16.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane16.setMinimumSize(new java.awt.Dimension(3, 23));

        InfoTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        InfoTel.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        InfoTel.setEnabled(false);
        jScrollPane16.setViewportView(InfoTel);

        Email1.setFont(new java.awt.Font("Ubuntu Light", 0, 17)); // NOI18N
        Email1.setText("Email:");

        Notas1.setFont(new java.awt.Font("Ubuntu Light", 0, 17)); // NOI18N
        Notas1.setText("Notas:");

        jScrollPane17.setEnabled(false);
        jScrollPane17.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        jScrollPane17.setMinimumSize(new java.awt.Dimension(3, 23));

        InfoEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        InfoEmail.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        InfoEmail.setEnabled(false);
        jScrollPane17.setViewportView(InfoEmail);

        jScrollPane18.setEnabled(false);
        jScrollPane18.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N

        InfoName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        InfoName.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        InfoName.setEnabled(false);
        jScrollPane18.setViewportView(InfoName);

        Contact_Pic1.setBackground(new java.awt.Color(255, 255, 255));
        Contact_Pic1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Contact_Pic1.setMaximumSize(new java.awt.Dimension(150, 150));
        Contact_Pic1.setMinimumSize(new java.awt.Dimension(150, 150));

        nonePic1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N

        javax.swing.GroupLayout Contact_Pic1Layout = new javax.swing.GroupLayout(Contact_Pic1);
        Contact_Pic1.setLayout(Contact_Pic1Layout);
        Contact_Pic1Layout.setHorizontalGroup(
            Contact_Pic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contact_Pic1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nonePic1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        Contact_Pic1Layout.setVerticalGroup(
            Contact_Pic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contact_Pic1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nonePic1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelDone.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        PanelDone.setText("Salir");

        SearchCon.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        SearchCon.setText("Buscar");
        SearchCon.setFocusPainted(false);

        SearchField.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        jScrollPane5.setViewportView(SearchField);

        UpdateCon.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        UpdateCon.setText("Actualizar");
        UpdateCon.setFocusable(false);

        EditCon.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        EditCon.setText("Editar");
        EditCon.setFocusPainted(false);

        DelCon.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        DelCon.setText("Borrar");
        DelCon.setFocusable(false);

        jScrollPane21.setEnabled(false);
        jScrollPane21.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N

        IDInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        IDInfo.setFont(new java.awt.Font("Ubuntu Light", 0, 16)); // NOI18N
        IDInfo.setEnabled(false);
        jScrollPane21.setViewportView(IDInfo);

        Nombre3.setFont(new java.awt.Font("Ubuntu Light", 0, 17)); // NOI18N
        Nombre3.setText("ID:");

        javax.swing.GroupLayout MultiPanelLayout = new javax.swing.GroupLayout(MultiPanel.getContentPane());
        MultiPanel.getContentPane().setLayout(MultiPanelLayout);
        MultiPanelLayout.setHorizontalGroup(
            MultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MultiPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(MultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MultiPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchCon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditCon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(UpdateCon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DelCon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MultiPanelLayout.createSequentialGroup()
                        .addComponent(Contact_Pic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(MultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Apellido1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Company1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Nombre3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Nombre1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(MultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Notas1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Pos1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Tel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Email1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(10, 10, 10)
                        .addGroup(MultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
            .addComponent(Header5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MultiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelDone, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MultiPanelLayout.setVerticalGroup(
            MultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MultiPanelLayout.createSequentialGroup()
                .addComponent(Header5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchCon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateCon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditCon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelCon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(MultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MultiPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Contact_Pic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MultiPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(MultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pos1)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre3))
                        .addGap(16, 16, 16)
                        .addGroup(MultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MultiPanelLayout.createSequentialGroup()
                                .addGroup(MultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tel1)
                                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(MultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Email1)
                                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(MultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Notas1)))
                            .addGroup(MultiPanelLayout.createSequentialGroup()
                                .addGroup(MultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MultiPanelLayout.createSequentialGroup()
                                        .addComponent(Nombre1)
                                        .addGap(18, 18, 18)
                                        .addComponent(Apellido1))
                                    .addGroup(MultiPanelLayout.createSequentialGroup()
                                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15)
                                .addGroup(MultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Company1)
                                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(PanelDone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        ImportContacts.setMinimumSize(new java.awt.Dimension(1020, 420));

        OpenCon.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        OpenCon.setText("Abrir ");
        OpenCon.setFocusPainted(false);

        FilePath.setEnabled(false);
        jScrollPane12.setViewportView(FilePath);

        CancelImp.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        CancelImp.setText("Cancelar");
        CancelImp.setFocusPainted(false);

        SaveCon.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        SaveCon.setText("Guardar");
        SaveCon.setFocusPainted(false);

        jPanel1.setBackground(new java.awt.Color(2, 136, 209));

        ImpCon.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        ImpCon.setForeground(new java.awt.Color(255, 255, 255));
        ImpCon.setText("Importar Contactos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(421, 421, 421)
                .addComponent(ImpCon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImpCon)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        ImportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Compañia", "Posicion", "Telefono", "Email", "Notas"
            }
        ));
        jScrollPane19.setViewportView(ImportTable);

        javax.swing.GroupLayout ImportContactsLayout = new javax.swing.GroupLayout(ImportContacts.getContentPane());
        ImportContacts.getContentPane().setLayout(ImportContactsLayout);
        ImportContactsLayout.setHorizontalGroup(
            ImportContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImportContactsLayout.createSequentialGroup()
                .addGroup(ImportContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ImportContactsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane19))
                    .addGroup(ImportContactsLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(OpenCon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                        .addComponent(CancelImp, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SaveCon, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ImportContactsLayout.setVerticalGroup(
            ImportContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImportContactsLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(ImportContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OpenCon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ImportContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CancelImp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SaveCon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(234, 242, 248));
        Background.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N

        Options.setBackground(new java.awt.Color(234, 242, 248));

        AddBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AddBtn.setText("Añadir");
        AddBtn.setFocusPainted(false);
        AddBtn.setPreferredSize(new java.awt.Dimension(104, 27));

        ImportBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ImportBtn.setText("Importar");
        ImportBtn.setFocusPainted(false);
        ImportBtn.setMinimumSize(new java.awt.Dimension(104, 27));
        ImportBtn.setPreferredSize(new java.awt.Dimension(104, 27));

        iconAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emil\\Desktop\\ITLA Homework\\3rd Cycle\\Prog I\\7. Proyecto Final (CRUD)\\assets\\ic_add_circle_24px.png")); // NOI18N

        iconImport.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emil\\Desktop\\ITLA Homework\\3rd Cycle\\Prog I\\7. Proyecto Final (CRUD)\\assets\\ic_import_contacts_24px.png")); // NOI18N

        iconEdit1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emil\\Desktop\\ITLA Homework\\3rd Cycle\\Prog I\\7. Proyecto Final (CRUD)\\assets\\ic_settings_24px.png")); // NOI18N

        OpenPanel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        OpenPanel.setText("Administrar");
        OpenPanel.setFocusPainted(false);

        javax.swing.GroupLayout OptionsLayout = new javax.swing.GroupLayout(Options);
        Options.setLayout(OptionsLayout);
        OptionsLayout.setHorizontalGroup(
            OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionsLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(iconAdd)
                    .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconEdit1)
                    .addComponent(OpenPanel)
                    .addComponent(iconImport)
                    .addComponent(ImportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        OptionsLayout.setVerticalGroup(
            OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionsLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(iconAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iconEdit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OpenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iconImport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ImportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Container.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ContactsContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 136, 209)));
        ContactsContainer.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        ContactsContainer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {{}},
            new String [] {
                "ID", "Nombre", "Apellido", "Compañia", "Posicion", "Telefono", "Email", "Notas"
            }
        ));
        ContactsContainer.setEnabled(false);
        ContactsContainer.setRowMargin(5);
        jScrollPane6.setViewportView(ContactsContainer);

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );

        Close.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Close.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emil\\Desktop\\ITLA Homework\\3rd Cycle\\Prog I\\7. Proyecto Final (CRUD)\\assets\\ic_close_24px.png")); // NOI18N
        Close.setFocusPainted(false);
        Close.setMaximumSize(new java.awt.Dimension(50, 40));
        Close.setMinimumSize(new java.awt.Dimension(50, 40));
        Close.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(Options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(Options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        getContentPane().add(Background, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(2, 136, 209));

        Title.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emil\\Desktop\\ITLA Homework\\3rd Cycle\\Prog I\\7. Proyecto Final (CRUD)\\assets\\ic_account_box_24px.png")); // NOI18N
        Title.setText("Mis Contactos - Java");

        RefreshBtn.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        RefreshBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emil\\Desktop\\ITLA Homework\\3rd Cycle\\Prog I\\7. Proyecto Final (CRUD)\\assets\\ic_refresh_24px.png")); // NOI18N
        RefreshBtn.setFocusPainted(false);
        RefreshBtn.setMaximumSize(new java.awt.Dimension(50, 50));
        RefreshBtn.setMinimumSize(new java.awt.Dimension(50, 50));
        RefreshBtn.setPreferredSize(new java.awt.Dimension(60, 40));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1025, Short.MAX_VALUE)
                .addComponent(RefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Set System L&F
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Core.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Core().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel Apellido1;
    private javax.swing.JPanel Background;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton CancelImp;
    private javax.swing.JButton Close;
    private javax.swing.JLabel Company;
    private javax.swing.JLabel Company1;
    public javax.swing.JPanel Contact_Pic;
    public javax.swing.JPanel Contact_Pic1;
    public javax.swing.JTable ContactsContainer;
    public javax.swing.JPanel Container;
    public javax.swing.JTextPane CorpField;
    private javax.swing.JButton DelCon;
    private javax.swing.JButton EditCon;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Email1;
    public javax.swing.JTextPane EmailField;
    private javax.swing.JTextPane FilePath;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Header2;
    private javax.swing.JPanel Header5;
    public javax.swing.JTextPane IDField;
    public javax.swing.JTextPane IDInfo;
    private javax.swing.JLabel ImpCon;
    private javax.swing.JButton ImportBtn;
    private javax.swing.JDialog ImportContacts;
    private javax.swing.JTable ImportTable;
    public javax.swing.JTextPane InfoCompany;
    public javax.swing.JTextPane InfoEmail;
    public javax.swing.JTextPane InfoLast;
    public javax.swing.JTextPane InfoName;
    public javax.swing.JTextPane InfoNotes;
    public javax.swing.JTextPane InfoPos;
    public javax.swing.JTextPane InfoTel;
    public javax.swing.JTextPane LNameField;
    private javax.swing.JDialog MultiPanel;
    public javax.swing.JTextPane NameField;
    public javax.swing.JDialog NewContact;
    private javax.swing.JLabel New_Con;
    private javax.swing.JLabel New_Con2;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Nombre3;
    private javax.swing.JLabel Notas;
    private javax.swing.JLabel Notas1;
    public javax.swing.JTextPane NotesField;
    public javax.swing.JTextPane NumField;
    private javax.swing.JButton OpenCon;
    private javax.swing.JButton OpenPanel;
    private javax.swing.JPanel Options;
    private javax.swing.JButton PanelDone;
    private javax.swing.JLabel Pos;
    private javax.swing.JLabel Pos1;
    public javax.swing.JTextPane PosField;
    private javax.swing.JButton RefreshBtn;
    private javax.swing.JButton SaveCon;
    private javax.swing.JButton SaveContact;
    private javax.swing.JButton SearchCon;
    private javax.swing.JTextPane SearchField;
    private javax.swing.JLabel Tel;
    private javax.swing.JLabel Tel1;
    private javax.swing.JLabel Title;
    private javax.swing.JButton UpdateCon;
    public javax.swing.JButton UploadPic;
    private javax.swing.JTextPane filePath;
    private javax.swing.JLabel iconAdd;
    private javax.swing.JLabel iconEdit1;
    private javax.swing.JLabel iconImport;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane10;
    public javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    public javax.swing.JScrollPane jScrollPane13;
    public javax.swing.JScrollPane jScrollPane14;
    public javax.swing.JScrollPane jScrollPane15;
    public javax.swing.JScrollPane jScrollPane16;
    public javax.swing.JScrollPane jScrollPane17;
    public javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane20;
    public javax.swing.JScrollPane jScrollPane21;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel nonePic;
    private javax.swing.JLabel nonePic1;
    // End of variables declaration//GEN-END:variables
    
    public void Initializer(){
        
        ContactHandler();
        Functions(); 
        filePath.setText("C:\\Users\\Emil\\Documents\\NetBeansProjects\\ContactsCRUD\\src\\main\\java\\CRUD\\UserPlaceholder.png");
    }
    
   
    
    public void Functions(){
        
        UploadPic.addActionListener((ActionEvent e) -> {
            ImageHandler();
        });
        
        // Cargando Contactos de la Base de Datos---------------------------------------
        RefreshBtn.addActionListener((ActionEvent e) -> {
            Data.LoadData(ContactsContainer, nonePic);
            });
        
        Close.addActionListener((ActionEvent e) -> {
            System.exit(0);
        });
        
        ImportBtn.addActionListener((ActionEvent e) -> {
            Ops.ImportHandler(ImportContacts, ImportTable, FilePath, OpenCon, SaveCon, CancelImp);
        });
    }
    
    public void ContactHandler() {        
         // Añadir un Contacto---------------------------------------------------------------------
        AddBtn.addActionListener((ActionEvent e) -> {
            Random r = new Random();
            int low = 1722;
            int high = 6076;
            int id = r.nextInt(high-low) + low;
            IDField.setText(Integer.toString(id));
            Ops.Launcher(NewContact);
        });
        
        
        // Guardar Contacto------------------------------------------------------------------------
        SaveContact.addActionListener((ActionEvent e) -> {
            try {
                Ops.AddContact(NewContact, nonePic, ContactsContainer, filePath, IDField, NameField, LNameField, CorpField, PosField, NumField, EmailField, NotesField);
                nonePic.setIcon(null);
                filePath.setText(null);
                Random r = new Random();
                int low = 1722;
                int high = 6076;
                int id = r.nextInt(high-low) + low;
                IDField.setText(Integer.toString(id));
            } catch (IOException ex) {
                Logger.getLogger(Core.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        
        
        // Cancelar Registro-------------------------------------------------------------------------
        CancelBtn.addActionListener((ActionEvent e) -> {
            JOptionPane.showMessageDialog(NewContact, "El registro fue cancelado."); 
            Ops.CleanFields(NameField, LNameField, CorpField, PosField, NumField, EmailField, NotesField);
            NewContact.dispose();
        });
        
        OpenPanel.addActionListener((ActionEvent e) -> {
            Ops.MultiPanel(MultiPanel, nonePic1, SearchCon, EditCon, UpdateCon, DelCon, SearchField, IDInfo, InfoName, InfoLast, InfoCompany, InfoPos, InfoTel, InfoEmail, InfoNotes);
        });
        
        PanelDone.addActionListener((ActionEvent e) -> {
            SearchField.setText(null);
            Ops.CleanFields(InfoName, InfoLast, InfoCompany, InfoPos, InfoTel, InfoEmail, InfoNotes);
            nonePic1.setIcon(null);
            IDInfo.setText(null);
            MultiPanel.dispose();
        });
        
        
    }
    
    public void icon() {
        try {
            URL url = new URL("https://assets.materialup.com/uploads/4cffc9ad-6078-4ad9-92db-67d4cf9dde0a/preview");
            Image image = ImageIO.read(url); 
            setIconImage(new ImageIcon(image).getImage());
        } catch(IOException Ex){
            System.out.println("No Connection - No Icon is provided.");
            Ex.printStackTrace();
        }        
        catch(Exception Ex){
            System.out.println("No Connection - No Icon is provided.");
            Ex.printStackTrace();
        }
    }
    
    public void ImageHandler() {
        try {
                JFileChooser chooser = new JFileChooser();
                FileNameExtensionFilter filter = new FileNameExtensionFilter("png", "jpg");
                chooser.setFileFilter(filter);
                int approve = chooser.showOpenDialog(null);
                if(approve == JFileChooser.APPROVE_OPTION){
                   File f = chooser.getSelectedFile();
                   String path = f.getAbsolutePath();
                   filePath.setText(path);
                   Image foto = getToolkit().getImage(path);
                   foto = foto.getScaledInstance(110, 110,Image.SCALE_DEFAULT);
                   nonePic.setIcon(new ImageIcon(foto));
                }
                } catch(HeadlessException Ex) {JOptionPane.showMessageDialog(null, Ex);}
    }
}
